name: TryTpa
version: 1.2-folia
folia-supported: true
api-version: 1.20
main: net.trysmp.tpa.TryTpa
author: VertrauterDavid recodet by TinyBrickBoy for Folia support
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/

commands:
  removetpaall:
  tpa:
  tpaccept:
  tpaaccept:
  tpahere:
  tpahereaccept:
  tpaall: