name: TryTpa
version: 1.1
api-version: 1.19
main: net.trysmp.tpa.TryTpa
author: VertrauterDavid
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/

commands:
  removetpaall:
  tpa:
  tpaccept:
  tpaaccept:
  tpahere:
  tpahereaccept:
  tpaall:
